apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: prediction-market-pg
    url: postgres:5432
    user: admin
    secureJsonData:
      password: changeme
    jsonData:
      database: prediction_market
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
